name: VeriliousMiscTools
author: Johnathan Runyon
version: 1.0
api-version: 1.13
main: com.runyontech.misctools.MiscTools
commands:
  launch:
    description: Launches the player
    usage: /<command>
    permission: misctools.launch